/**
 * Types for the "Coin Story" feature of /ancestor.
 *
 * A "story" is a first-person autobiographical narrative of a cryptocurrency,
 * generated by an LLM grounded in Tavily research results. This module is
 * the contract shared by the research layer, the story generator, the
 * Supabase persistence layer, and the UI.
 */

/**
 * A single historical fact about a coin, extracted from a Tavily search.
 *
 * `confidence` is a 0..1 estimate of how strongly the source supports the
 * fact. The story generator MUST only use facts above the minimum
 * threshold and MUST attribute each one back to its source URL.
 */
export interface HistoricalFact {
  /** Short, declarative statement. e.g. "Created by Satoshi Nakamoto" */
  claim: string;
  /** Optional year or date. e.g. "2008", "2009-01-03", or null. */
  date: string | null;
  /** 0..1 — how confident we are in this fact given the sources. */
  confidence: number;
  /** Source URLs supporting this fact. */
  sourceUrls: string[];
}

/**
 * A source surfaced by Tavily for a particular research query.
 *
 * `relevance` is the Tavily score (0..1). `publishedAt` is best-effort
 * — many sources don't expose a date, so it can be null.
 */
export interface ResearchSource {
  title: string;
  url: string;
  domain: string;
  /** Brief excerpt from the source. */
  snippet: string;
  /** 0..1 relevance score from Tavily. */
  relevance: number;
  /** Best-effort publish date. */
  publishedAt: string | null;
}

/**
 * Structured historical research output for a single coin.
 */
export interface CoinResearch {
  symbol: string;
  /** Display name, e.g. "Bitcoin". */
  name: string;
  /** The fact set the story generator will use. */
  facts: HistoricalFact[];
  /** Ordered list of sources supporting the facts. */
  sources: ResearchSource[];
  /** Hash of the research input (symbol + name + sources) — used for cache keys. */
  researchHash: string;
  /** ISO timestamp the research was last refreshed. */
  researchedAt: string;
}

/**
 * A single timeline point derived from facts — used by the optional
 * interactive timeline on the story page.
 */
export interface TimelinePoint {
  /** Year or partial date string, e.g. "2008". */
  date: string;
  /** Short label. */
  label: string;
  /** Index into the story paragraph that this point corresponds to. */
  paragraphIndex: number;
}

/**
 * The generated first-person story for a coin.
 *
 * Persisted in Supabase and re-used on subsequent visits so we don't
 * call Tavily + an LLM on every page load.
 */
export interface CoinStory {
  symbol: string;
  name: string;
  /** Title shown above the story. e.g. "The Story of Bitcoin". */
  title: string;
  /** Opening quote / hook. e.g. "I am Bitcoin.". */
  hook: string;
  /** Ordered paragraphs that compose the story. */
  paragraphs: string[];
  /** Optional timeline points derived from the facts. */
  timeline: TimelinePoint[];
  /** The sources backing the story, in display order. */
  sources: ResearchSource[];
  /** Hash of the research input — used to invalidate the cache. */
  researchHash: string;
  /** Generation metadata. */
  generatedAt: string;
  /** True if the LLM decided it didn't have enough material for a story. */
  fallback: boolean;
}